"""Calibrate static Autogain for the independent-path Hybrid. No Drive remapping here.
Usage: python calibrate_hybrid.py /path/to/current.vst3
Autogain is disabled during measurement, so existing compensation does not affect fitting.
--export-existing regenerates the header from the saved calibration report.
"""
from pathlib import Path
import importlib.util,json,sys
import numpy as np
import pyloudnorm as pyln
from pedalboard import load_plugin
root=Path(__file__).resolve().parents[2]
def export_tables(report):
 values=report['autogain_db']
 text='#pragma once\n// Generated by tools/grit_model/calibrate_hybrid.py; do not edit.\n#include <array>\nnamespace bqt::grithybrid {\n'
 text+=f'inline constexpr std::array<double, {len(values)}> autoGainDb {{ '+', '.join(f'{v:.17g}' for v in values)+' };\n}\n'
 (root/'src/BqtGritHybridParams.h').write_text(text)
if len(sys.argv)!=2:raise SystemExit(__doc__)
if sys.argv[1]=='--export-existing':
 report=json.loads((root/'tools/grit_model/hybrid_calibration.json').read_text())
 if report.get('revision')!=2:raise SystemExit('Refit the independent-path Hybrid first.')
 export_tables(report);raise SystemExit(0)
spec=importlib.util.spec_from_file_location('cal',root/'tools/calibrate_autogain.py');cal=importlib.util.module_from_spec(spec);spec.loader.exec_module(cal)
p=load_plugin(str(Path(sys.argv[1]).resolve()));p.grit_model='Hybrid';p.l_m_type='Grit';p.r_s_type='Grit';p.l_m_mix=100;p.r_s_mix=100;p.autogain=False;p.vintage=False;p.realtime_os='4x';p.render_os='4x'
mats={n:np.asarray(x,dtype='float32') for n,x in cal.materials.items()};meter=pyln.Meter(48000)
base={n:meter.integrated_loudness(x) for n,x in mats.items()};rows=[];gains=[]
for k in np.arange(0,18.001,.5):
 p.l_m_drive=float(k);p.r_s_drive=float(k);deltas={}
 for name,x in mats.items():
  # Silence settles control smoothing before each material; avoid fitting automation transients.
  padded=np.r_[np.zeros(48000,dtype='float32'),x]
  y=p(np.tile(padded,(2,1)),48000,buffer_size=512)[0,48000:]
  deltas[name]=float(meter.integrated_loudness(y)-base[name])
 gain=-float(np.median(list(deltas.values()))) if k else 0.;gains.append(gain)
 rows.append({'knob':float(k),'compensation_db':gain,'residual_lu':{n:v+gain for n,v in deltas.items()}})
 if k%3==0:print(rows[-1],flush=True)
report={'revision':2,'method':'75% complete Legacy at original Drive + 25% complete Captured at independently remapped Drive. Captured aligned using its calibrated gain relative to legacy compensation before mixing. Static blend Autogain targets median 0 LU across five sources; 48 kHz, 4x OS, Vintage off, one second silence before each material.','autogain_db':gains,'materials':rows}
(root/'tools/grit_model/hybrid_calibration.json').write_text(json.dumps(report,indent=2)+'\n');export_tables(report)
