"""Export bounded, odd lookup tables for the experimental LA500A capture fit.
Run with Python + NumPy: python tools/grit_model/export.py
No captured audio is required to regenerate the shipped constants.
"""
from pathlib import Path
import json
import numpy as np
root=Path(__file__).resolve().parents[2]
p=json.loads(Path(__file__).with_name('fit.json').read_text())
driven=json.loads(Path(__file__).with_name('driven_fit.json').read_text())
n=8193;maximum=32.0;x=maximum*(np.arange(n)/(n-1))**2
lines=['#pragma once','// Generated by tools/grit_model/export.py. Experimental whole-path fit, not an isolated transformer.', '#include <array>', 'namespace bqt::gritlab {', f'inline constexpr int tableSize = {n};',f'inline constexpr double tableMaximum = {maximum};',f'inline constexpr double direct = {p["direct"]:.17g};']
def arr(name,values):lines.append(f'inline constexpr std::array<double, {len(values)}> {name} {{ '+', '.join(f'{v:.17g}' for v in values)+' };')
calibration=json.loads(Path(__file__).with_name('calibration.json').read_text())
arr('referenceKnob',calibration['reference_knob']);arr('autoGainDb',calibration['autogain_db'])
arr('knobDb',driven['knob_db']);arr('makeupDb',driven['makeup_db'])
lines.append(f'inline constexpr double outputThreshold = {driven["threshold"]:.17g};')
lines.append(f'inline constexpr double outputKnee = {driven["knee"]:.17g};')
arr('poles',p['poles']);arr('coreFrequencies',p['core_frequencies']);arr('coreWeights',p['core_weights']);arr('linearSlopes',[w[0] for w in p['weights']])
lines.append(f'inline constexpr std::array<std::array<float, tableSize>, {len(p["poles"])}> tables {{{{')
for weights in p['weights']:
 y=weights[0]*x
 for threshold,w in zip(p['thresholds'],weights[1:]):y+=w*threshold*np.tanh(x/threshold)
 lines.append('    {{')
 for i in range(0,n,8):lines.append('        '+', '.join(f'{v:.9e}f' for v in y[i:i+8])+',')
 lines.append('    }},')
lines+=['}};','} // namespace bqt::gritlab','']
(root/'src/BqtGritLabParams.h').write_text('\n'.join(lines))
