param(
    [string] $BuildDir = "build-windows",
    [string] $Config = "Release",
    [string] $InnoSetupCompiler = "ISCC.exe"
)

$ErrorActionPreference = "Stop"

$RootDir = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$BuildPath = Join-Path $RootDir $BuildDir
$Vst3Path = Join-Path $BuildPath "BQST_artefacts\$Config\VST3\BQST.vst3"

# Version comes from CMakeLists.txt; nothing here restates it.
$CMakeLists = Join-Path $RootDir "CMakeLists.txt"
$VersionMatch = Select-String -Path $CMakeLists -Pattern 'project\(\s*BQST\s+VERSION\s+(\d+\.\d+\.\d+)' | Select-Object -First 1
if (-not $VersionMatch) {
    throw "Could not read the project version from $CMakeLists (expected: project(BQST VERSION x.y.z ...))"
}
$Version = $VersionMatch.Matches[0].Groups[1].Value

$InstallerPath = Join-Path $RootDir "dist\BQST-$Version-Windows.exe"
# Generated by CMake from packaging/windows/BQST.iss.in during configure.
$InstallerScript = Join-Path $BuildPath "packaging\windows\BQST.iss"

if ((Test-Path $InstallerPath) -and -not $env:OVERWRITE_EXISTING_PKG) {
    throw "Refusing to overwrite an existing installer: $InstallerPath. Bump project(... VERSION ...) in CMakeLists.txt, or set OVERWRITE_EXISTING_PKG=1."
}

if (-not (Test-Path $Vst3Path)) {
    throw "Missing VST3 artifact: $Vst3Path. Run: cmake --build $BuildDir --config $Config"
}

$Iscc = Get-Command $InnoSetupCompiler -ErrorAction SilentlyContinue
if (-not $Iscc) {
    $DefaultIscc = "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe"
    if (Test-Path $DefaultIscc) {
        $InnoSetupCompiler = $DefaultIscc
    } else {
        throw "Inno Setup compiler not found. Install Inno Setup 6 or pass -InnoSetupCompiler."
    }
}

New-Item -ItemType Directory -Force -Path (Join-Path $RootDir "dist") | Out-Null
& $InnoSetupCompiler $InstallerScript

if (-not (Test-Path $InstallerPath)) {
    throw "Installer was not created: $InstallerPath"
}

Write-Host "Built installer: $InstallerPath"
