#!/usr/bin/env python3
"""Grit autogain calibration sweep, plus the shared test materials.

Cream autogain is generated by tools/cream_model (density.bqst_export), which imports the
material generators below. Run: uv run --no-project python tools/calibrate_autogain.py
"""

import math
from dataclasses import dataclass


sample_rate = 48000.0
duration_seconds = 3.0
num_samples = int(sample_rate * duration_seconds)
drive_scale = 0.40
coloration_ramp_scale = 3.0  # colorationRampScale: full colour at 6 dB of the 18 dB range
dc_blocker_hz = 5.0


@dataclass
class Biquad:
    b0: float
    b1: float
    b2: float
    a1: float
    a2: float
    z1: float = 0.0
    z2: float = 0.0

    def process(self, x):
        y = self.b0 * x + self.z1
        self.z1 = self.b1 * x - self.a1 * y + self.z2
        self.z2 = self.b2 * x - self.a2 * y
        return y


def db_to_gain(db):
    return 10.0 ** (db / 20.0)


def make_low_shelf(freq, q, gain):
    a = math.sqrt(gain)
    w0 = 2.0 * math.pi * freq / sample_rate
    cos_w0 = math.cos(w0)
    sin_w0 = math.sin(w0)
    alpha = sin_w0 / (2.0 * q)
    beta = 2.0 * math.sqrt(a) * alpha

    b0 = a * ((a + 1.0) - (a - 1.0) * cos_w0 + beta)
    b1 = 2.0 * a * ((a - 1.0) - (a + 1.0) * cos_w0)
    b2 = a * ((a + 1.0) - (a - 1.0) * cos_w0 - beta)
    a0 = (a + 1.0) + (a - 1.0) * cos_w0 + beta
    a1 = -2.0 * ((a - 1.0) + (a + 1.0) * cos_w0)
    a2 = (a + 1.0) + (a - 1.0) * cos_w0 - beta
    return Biquad(b0 / a0, b1 / a0, b2 / a0, a1 / a0, a2 / a0)


def make_high_shelf(freq, q, gain):
    a = math.sqrt(gain)
    w0 = 2.0 * math.pi * freq / sample_rate
    cos_w0 = math.cos(w0)
    sin_w0 = math.sin(w0)
    alpha = sin_w0 / (2.0 * q)
    beta = 2.0 * math.sqrt(a) * alpha

    b0 = a * ((a + 1.0) + (a - 1.0) * cos_w0 + beta)
    b1 = -2.0 * a * ((a - 1.0) + (a + 1.0) * cos_w0)
    b2 = a * ((a + 1.0) + (a - 1.0) * cos_w0 - beta)
    a0 = (a + 1.0) - (a - 1.0) * cos_w0 + beta
    a1 = 2.0 * ((a - 1.0) - (a + 1.0) * cos_w0)
    a2 = (a + 1.0) - (a - 1.0) * cos_w0 - beta
    return Biquad(b0 / a0, b1 / a0, b2 / a0, a1 / a0, a2 / a0)


def make_peak(freq, q, gain):
    a = math.sqrt(gain)
    w0 = 2.0 * math.pi * freq / sample_rate
    cos_w0 = math.cos(w0)
    sin_w0 = math.sin(w0)
    alpha = sin_w0 / (2.0 * q)

    b0 = 1.0 + alpha * a
    b1 = -2.0 * cos_w0
    b2 = 1.0 - alpha * a
    a0 = 1.0 + alpha / a
    a1 = -2.0 * cos_w0
    a2 = 1.0 - alpha / a
    return Biquad(b0 / a0, b1 / a0, b2 / a0, a1 / a0, a2 / a0)


def transformer_saturate(sample, drive01):
    if drive01 <= 0.0:
        return sample

    push = drive01 * drive01
    max_push = push * drive01
    drive = 0.92 + drive01 * 1.55 + push * 0.82 + max_push * 1.15
    bias = 0.018 * drive01 + push * 0.010 + max_push * 0.018
    tanh_norm = math.tanh(0.86)
    biased = sample * drive + bias
    shaped = math.tanh(biased * 0.86) / tanh_norm - math.tanh(bias * 0.86) / tanh_norm
    rounded = shaped - (0.025 * drive01 + 0.014 * push + 0.020 * max_push) * shaped * shaped * shaped
    blend = drive01 * 0.43 + push * 0.12 + max_push * 0.14
    return sample * (1.0 - blend) + rounded * blend


def process_saturation(samples, drive01):
    """Grit's wet path, mirroring the plugin's processSide Grit branch (Vintage off, before autogain).

    The linear filters and the 5 Hz DC blocker are blended toward their input by the colour ramp
    min(1, coloration_ramp_scale * drive01), as in the plugin.
    """
    pre_low = make_low_shelf(95.0, 0.55, db_to_gain(-2.2))
    post_low = make_low_shelf(95.0, 0.55, db_to_gain(2.2))
    low_drive = make_low_shelf(165.0, 0.62, db_to_gain(1.10))
    weight = make_peak(245.0, 0.72, db_to_gain(0.55))
    low_restore = make_low_shelf(165.0, 0.62, db_to_gain(-0.70))
    top = make_high_shelf(7800.0, 0.50, db_to_gain(-0.75))

    gain = db_to_gain(drive01 * 18.0 * drive_scale)
    color = min(1.0, drive01 * coloration_ramp_scale)
    dc_coefficient = math.exp(-2.0 * math.pi * dc_blocker_hz / sample_rate)
    previous_input = 0.0
    previous_output = 0.0

    def colored(filt, x):
        return x + (filt.process(x) - x) * color

    out = []
    for sample in samples:
        value = colored(pre_low, sample)
        value = colored(low_drive, value)
        value = colored(weight, value)
        value = transformer_saturate(value * gain, drive01)
        value = colored(low_restore, value)
        value = colored(top, value)
        value = colored(post_low, value)

        blocked = value - previous_input + dc_coefficient * previous_output
        previous_input = value
        previous_output = blocked
        value += (blocked - value) * color
        out.append(value)
    return out


def rms_db(samples):
    start = int(0.25 * sample_rate)
    usable = samples[start:]
    mean_square = sum(x * x for x in usable) / max(1, len(usable))
    return 10.0 * math.log10(max(mean_square, 1.0e-16))


def crest_db(samples):
    rms = db_to_gain(rms_db(samples))
    peak = max(abs(x) for x in samples)
    return 20.0 * math.log10(max(peak, 1.0e-12) / max(rms, 1.0e-12))


def normalize_peak(samples, peak_db):
    peak = max(abs(x) for x in samples)
    if peak <= 0.0:
        return samples
    gain = db_to_gain(peak_db) / peak
    return [x * gain for x in samples]


def sine(freq):
    return [math.sin(2.0 * math.pi * freq * i / sample_rate) for i in range(num_samples)]


def bass_808():
    out = []
    phase = 0.0
    for i in range(num_samples):
        t = i / sample_rate
        local = t % 0.75
        freq = 42.0 + 34.0 * math.exp(-local * 11.0)
        phase += 2.0 * math.pi * freq / sample_rate
        env = math.exp(-local * 4.0)
        out.append(math.sin(phase) * env)
    return out


def bassline():
    notes = [55.0, 73.42, 49.0, 65.41, 41.2, 55.0, 82.41, 61.74]
    out = []
    for i in range(num_samples):
        t = i / sample_rate
        step = int((t * 4.0) % len(notes))
        local = (t * 4.0) % 1.0
        env = min(1.0, local * 20.0) * math.exp(-local * 1.2)
        f = notes[step]
        saw = 2.0 * ((t * f) % 1.0) - 1.0
        sub = math.sin(2.0 * math.pi * f * 0.5 * t)
        out.append((0.58 * saw + 0.55 * sub) * env)
    return out


def drums():
    out = []
    for i in range(num_samples):
        t = i / sample_rate
        beat = t % 0.5
        kick = math.sin(2.0 * math.pi * (52.0 + 80.0 * math.exp(-beat * 55.0)) * t) * math.exp(-beat * 28.0)
        snare_phase = (t - 0.25) % 0.5
        snare_noise = math.sin(2.0 * math.pi * 1737.0 * t) * math.sin(2.0 * math.pi * 3181.0 * t)
        snare = snare_noise * math.exp(-snare_phase * 34.0) if snare_phase < 0.18 else 0.0
        hat_phase = t % 0.125
        hat = math.sin(2.0 * math.pi * 7600.0 * t) * math.exp(-hat_phase * 95.0)
        out.append(0.95 * kick + 0.25 * snare + 0.12 * hat)
    return out


def dense_master():
    out = []
    for i in range(num_samples):
        t = i / sample_rate
        low = 0.45 * math.sin(2.0 * math.pi * 58.0 * t)
        low += 0.26 * math.sin(2.0 * math.pi * 116.0 * t + 0.4)
        mid = 0.18 * math.sin(2.0 * math.pi * 440.0 * t)
        mid += 0.13 * math.sin(2.0 * math.pi * 880.0 * t + 1.1)
        air = 0.06 * math.sin(2.0 * math.pi * 6200.0 * t)
        groove = 0.82 + 0.18 * math.sin(2.0 * math.pi * 2.0 * t)
        out.append((low + mid + air) * groove)
    return out


materials = {
    "1k sine": normalize_peak(sine(1000.0), -12.0),
    "bass 808": normalize_peak(bass_808(), -1.0),
    "bassline": normalize_peak(bassline(), -3.0),
    "drum bus": normalize_peak(drums(), -1.0),
    "dense master": normalize_peak(dense_master(), -1.0),
}


drives_db = [0.5, 1.0, 2.0, 3.0, 6.0, 9.0, 12.0, 15.0, 18.0]


def target_table():
    rows = []
    for drive_db in drives_db:
        drive01 = drive_db / 18.0
        targets = []
        for name, samples in materials.items():
            dry = rms_db(samples)
            wet = rms_db(process_saturation(samples, drive01))
            target = dry - wet
            targets.append((name, target))
        rows.append((drive_db, targets))
    return rows


def model_gain_db(drive_db, amount, exponent):
    drive01 = drive_db / 18.0
    gain = 1.0 / (1.0 + (drive01 ** exponent) * amount)
    return 20.0 * math.log10(gain)


def fit_curve(rows):
    data = []
    for drive_db, targets in rows:
        for _, target in targets:
            data.append((drive_db, target))

    best = None
    for amount_i in range(40, 401):
        amount = amount_i / 100.0
        for exp_i in range(60, 251):
            exponent = exp_i / 100.0
            error = 0.0
            for drive_db, target in data:
                predicted = model_gain_db(drive_db, amount, exponent)
                error += (predicted - target) ** 2
            score = error / len(data)
            if best is None or score < best[0]:
                best = (score, amount, exponent)
    return best


def print_report():
    rows = target_table()
    score, amount, exponent = fit_curve(rows)
    print(f"\nGRIT autogain fit: amount={amount:.2f}, exponent={exponent:.2f}, rmse={math.sqrt(score):.2f} dB")
    print("drive | model | avg target | spread | material targets")
    for drive_db, targets in rows:
        values = [target for _, target in targets]
        avg = sum(values) / len(values)
        spread = max(values) - min(values)
        details = ", ".join(f"{name} {target:+.1f}" for name, target in targets)
        print(f"{drive_db:>4.1f} | {model_gain_db(drive_db, amount, exponent):>+5.1f} | {avg:>+6.1f} | {spread:>4.1f} | {details}")

    print("\nPrevious-model comparison:")
    previous_amount, previous_exponent = 2.71, 1.48  # shipped in bqt::saturationAutoGain
    for drive_db, targets in rows:
        avg = sum(target for _, target in targets) / len(targets)
        previous = model_gain_db(drive_db, previous_amount, previous_exponent)
        fitted = model_gain_db(drive_db, amount, exponent)
        print(f"{drive_db:>4.1f} dB: previous {previous:+5.1f} dB, fitted {fitted:+5.1f} dB, avg target {avg:+5.1f} dB")


if __name__ == "__main__":
    print("Material levels:")
    for name, samples in materials.items():
        print(f"{name:>12}: rms {rms_db(samples):>5.1f} dBFS, crest {crest_db(samples):>4.1f} dB")

    print_report()
